FROM golang:1.17 AS build
WORKDIR /go/src/gitstafette
ARG TARGETARCH
ARG TARGETOS
COPY go.* ./
RUN go mod download
COPY . ./
RUN make go-build-client

FROM alpine:3
RUN apk --no-cache add ca-certificates
EXPOSE 8080
ENV PORT=8080
ENV ROOT_PATH="/"
ENTRYPOINT ["/usr/bin/gitstafette"]
COPY --from=build /go/src/gitstafette/bin/gitstafette /usr/bin/gitstafette