// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/v1/gitstafette.proto

package gitstafette_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId            string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RepositoryId        string `protobuf:"bytes,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	LastReceivedEventId uint64 `protobuf:"varint,3,opt,name=last_received_event_id,json=lastReceivedEventId,proto3" json:"last_received_event_id,omitempty"`
	DurationSecs        uint32 `protobuf:"varint,4,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
}

func (x *WebhookEventsRequest) Reset() {
	*x = WebhookEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventsRequest) ProtoMessage() {}

func (x *WebhookEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEventsRequest.ProtoReflect.Descriptor instead.
func (*WebhookEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookEventsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WebhookEventsRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *WebhookEventsRequest) GetLastReceivedEventId() uint64 {
	if x != nil {
		return x.LastReceivedEventId
	}
	return 0
}

func (x *WebhookEventsRequest) GetDurationSecs() uint32 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

type WebhookEventPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode        string `protobuf:"bytes,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseDescription string `protobuf:"bytes,2,opt,name=response_description,json=responseDescription,proto3" json:"response_description,omitempty"`
	Accepted            bool   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *WebhookEventPushResponse) Reset() {
	*x = WebhookEventPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEventPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventPushResponse) ProtoMessage() {}

func (x *WebhookEventPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEventPushResponse.ProtoReflect.Descriptor instead.
func (*WebhookEventPushResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookEventPushResponse) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *WebhookEventPushResponse) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

func (x *WebhookEventPushResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type WebhookEventPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CliendId     string        `protobuf:"bytes,1,opt,name=cliend_id,json=cliendId,proto3" json:"cliend_id,omitempty"`
	RepositoryId string        `protobuf:"bytes,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	WebhookEvent *WebhookEvent `protobuf:"bytes,3,opt,name=webhook_event,json=webhookEvent,proto3" json:"webhook_event,omitempty"`
}

func (x *WebhookEventPushRequest) Reset() {
	*x = WebhookEventPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEventPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventPushRequest) ProtoMessage() {}

func (x *WebhookEventPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEventPushRequest.ProtoReflect.Descriptor instead.
func (*WebhookEventPushRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookEventPushRequest) GetCliendId() string {
	if x != nil {
		return x.CliendId
	}
	return ""
}

func (x *WebhookEventPushRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *WebhookEventPushRequest) GetWebhookEvent() *WebhookEvent {
	if x != nil {
		return x.WebhookEvent
	}
	return nil
}

type WebhookEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebhookEvents []*WebhookEvent `protobuf:"bytes,1,rep,name=webhook_events,json=webhookEvents,proto3" json:"webhook_events,omitempty"`
}

func (x *WebhookEventsResponse) Reset() {
	*x = WebhookEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventsResponse) ProtoMessage() {}

func (x *WebhookEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEventsResponse.ProtoReflect.Descriptor instead.
func (*WebhookEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookEventsResponse) GetWebhookEvents() []*WebhookEvent {
	if x != nil {
		return x.WebhookEvents
	}
	return nil
}

type WebhookEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string    `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Body    []byte    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers []*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{4}
}

func (x *WebhookEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WebhookEvent) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values string `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_gitstafette_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_gitstafette_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_api_v1_gitstafette_proto_rawDescGZIP(), []int{5}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

var File_api_v1_gitstafette_proto protoreflect.FileDescriptor

var file_api_v1_gitstafette_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66,
	0x65, 0x74, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x69, 0x74, 0x73,
	0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xb2, 0x01, 0x0a, 0x14, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x73, 0x22,
	0x8e, 0x01, 0x0a, 0x18, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x31, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x22, 0x9e, 0x01, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x41,
	0x0a, 0x0d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65,
	0x74, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x5c, 0x0a, 0x15, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x0d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x6f, 0x0a, 0x0c, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x30,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x22, 0x34, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0xdd, 0x01, 0x0a, 0x0b, 0x47, 0x69, 0x74, 0x73, 0x74,
	0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x67,
	0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x67, 0x0a,
	0x10, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73,
	0x68, 0x12, 0x27, 0x2e, 0x67, 0x69, 0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x67, 0x69, 0x74,
	0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x6f, 0x73, 0x74, 0x76, 0x64, 0x67, 0x2f, 0x67, 0x69,
	0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x69,
	0x74, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_gitstafette_proto_rawDescOnce sync.Once
	file_api_v1_gitstafette_proto_rawDescData = file_api_v1_gitstafette_proto_rawDesc
)

func file_api_v1_gitstafette_proto_rawDescGZIP() []byte {
	file_api_v1_gitstafette_proto_rawDescOnce.Do(func() {
		file_api_v1_gitstafette_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_gitstafette_proto_rawDescData)
	})
	return file_api_v1_gitstafette_proto_rawDescData
}

var file_api_v1_gitstafette_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_gitstafette_proto_goTypes = []interface{}{
	(*WebhookEventsRequest)(nil),     // 0: gitstafette.v1.WebhookEventsRequest
	(*WebhookEventPushResponse)(nil), // 1: gitstafette.v1.WebhookEventPushResponse
	(*WebhookEventPushRequest)(nil),  // 2: gitstafette.v1.WebhookEventPushRequest
	(*WebhookEventsResponse)(nil),    // 3: gitstafette.v1.WebhookEventsResponse
	(*WebhookEvent)(nil),             // 4: gitstafette.v1.WebhookEvent
	(*Header)(nil),                   // 5: gitstafette.v1.Header
}
var file_api_v1_gitstafette_proto_depIdxs = []int32{
	4, // 0: gitstafette.v1.WebhookEventPushRequest.webhook_event:type_name -> gitstafette.v1.WebhookEvent
	4, // 1: gitstafette.v1.WebhookEventsResponse.webhook_events:type_name -> gitstafette.v1.WebhookEvent
	5, // 2: gitstafette.v1.WebhookEvent.headers:type_name -> gitstafette.v1.Header
	0, // 3: gitstafette.v1.Gitstafette.FetchWebhookEvents:input_type -> gitstafette.v1.WebhookEventsRequest
	2, // 4: gitstafette.v1.Gitstafette.WebhookEventPush:input_type -> gitstafette.v1.WebhookEventPushRequest
	3, // 5: gitstafette.v1.Gitstafette.FetchWebhookEvents:output_type -> gitstafette.v1.WebhookEventsResponse
	1, // 6: gitstafette.v1.Gitstafette.WebhookEventPush:output_type -> gitstafette.v1.WebhookEventPushResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_gitstafette_proto_init() }
func file_api_v1_gitstafette_proto_init() {
	if File_api_v1_gitstafette_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_gitstafette_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_gitstafette_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEventPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_gitstafette_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEventPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_gitstafette_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_gitstafette_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_gitstafette_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_gitstafette_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_gitstafette_proto_goTypes,
		DependencyIndexes: file_api_v1_gitstafette_proto_depIdxs,
		MessageInfos:      file_api_v1_gitstafette_proto_msgTypes,
	}.Build()
	File_api_v1_gitstafette_proto = out.File
	file_api_v1_gitstafette_proto_rawDesc = nil
	file_api_v1_gitstafette_proto_goTypes = nil
	file_api_v1_gitstafette_proto_depIdxs = nil
}
