apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitstafette-config.fullname" . }}
  labels:
    {{- include "gitstafette-config.labels" . | nindent 4 }}
  annotations:
    projectcontour.io/upstream-protocol.h2c: "{{ .Values.grpcPort }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
      protocol: TCP
  selector:
    {{- include "gitstafette-config.selectorLabels" . | nindent 4 }}
