repositories: "537845873"

image:
  tag: "0.1.0-6ed49ec"
  pullPolicy: Always

grpcServer:
  host: gitstafette-server.gitstafette.svc.cluster.local
  port: 50051
  insecureFlag: insecure


resources:
  limits:
    memory: 16Mi
  requests:
    cpu: 250m
    memory: 16Mi
