repositories: "537845873"
grpcPort: 50051
httpPort: 1323
httpPrefix: "/"

image:
  tag: "0.1.0-6ed49ec"
  pullPolicy: Always

resources:
  limits:
    memory: 16Mi
  requests:
    cpu: 250m
    memory: 16Mi

httpproxy:
  enabled: true
  fqdn: lemon.fritz.box
  grpc:
    prefix: /
    replacement: /
  http:
    prefix: /api
    replacement: /

ingress:
  enabled: false