repositories: "537845873"
grpcPort: 8080
httpPort: 8080
httpPrefix: "/api"

image:
  #tag: "0.1.0-a45667a"
  tag: "0.1.0-6a88894-gcr"
  pullPolicy: Always

resources:
  limits:
    memory: 16Mi
  requests:
    cpu: 250m
    memory: 16Mi

httpproxy:
  enabled: true
  fqdn: lemon.fritz.box
  grpc:
    prefix: /
    replacement: /
  http:
    prefix: /api
    replacement: /api

ingress:
  enabled: false