services:
  cert-copy:
    image: bitnami/minideb:latest
    restart: unless-stopped
    command: ["./etc/copy_script.sh"]
    depends_on:
      - certbot
    configs:
      - source: copy_script
        target: /etc/copy_script.sh
    volumes:
      - certbot-certificates:/etc/certbot/certificates:ro
      - certbot-cmg-certificates:/etc/certbot/certificates-cmg:ro
      - envoy-certificates:/etc/envoy/certificates:rw
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 60s
      resources:
        limits:
          cpus: '0.15'
          memory: 20M

  certbot:
    image: certbot/dns-route53:arm64v8-v2.11.0
    command: [ "certonly", "-v", "--dns-route53", "-d", "events.gitstafette.joostvdg.net", "--email", "joostvdg@gmail.com", "--keep-until-expiring", "--agree-tos", "--non-interactive" ]
    volumes:
      - certbot-certificates:/etc/letsencrypt
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 60s
      resources:
        limits:
          cpus: '0.15'
          memory: 80M
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override.env
        required: false

  certbot-cmg:
    image: certbot/dns-route53:arm64v8-v2.11.0
    command: [ "certonly", "-v", "--dns-route53", "-d", "map.cmg.joostvdg.net","-d", "be.cmg.joostvdg.net",  "--email", "joostvdg@gmail.com", "--keep-until-expiring", "--agree-tos", "--non-interactive", "--expand" ]
    volumes:
      - certbot-cmg-certificates:/etc/letsencrypt
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 60s
      resources:
        limits:
          cpus: '0.15'
          memory: 80M
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override.env
        required: false

  envoy:
    image: envoyproxy/envoy:v1.31.0
    configs:
      - source: envoy_proxy
        target: /etc/envoy/envoy-proxy.yaml
        uid: "103"
        gid: "103"
        mode: 0440
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-proxy.yaml -l debug
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
    depends_on:
      - cert-copy
      - gitstafette-server
    volumes:
      - type: volume
        source: envoy-certificates
        target: /etc/envoy/certificates
    ports:
      - 443:443
      - 8081:8081
      - 8082:8082

  gitstafette-server:
    image: ghcr.io/joostvdg/gitstafette/server:0.3.0 #ghcr.io/joostvdg/gitstafette/server:0.1.0-3dfea6d
    command: [
      "--repositories=537845873,478599060,758715872,763032882,502306743",
      "--grpcPort=50051",
      "--port=1323",
      "--grpcHealthPort=50051",
      "--caFileLocation=/run/secrets/ca.cert",
      "--certFileLocation=/run/secrets/server.cert",
      "--certKeyFileLocation=/run/secrets/server.key"
    ]
    secrets:
      - source: certificate
        target: server.cert
        uid: "103"
        gid: "103"
        mode: 0440
      - source: certificate-key
        target: server.key
        uid: "103"
        gid: "103"
        mode: 0440
      - source: ca
        target: ca.cert
        uid: "103"
        gid: "103"
        mode: 0440
    ports:
      - "8080:1323"
      - "50051:50051"
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override.env
        required: false
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
      resources:
        limits:
          memory: 30M

  cmg:
    image: ghcr.io/joostvdg/cmg:0.3.3
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override-cmg.env
        required: false
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
      resources:
        limits:
          memory: 30M

  cmg-ui:
    image: ghcr.io/joostvdg/cmg-ui:1.1.0
    depends_on:
      - cmg
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override-cmg.env
        required: false
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
      resources:
        limits:
          memory: 100M

secrets:
  certificate:
    file: ./certs/events-aws.pem
  certificate-key:
    file: ./certs/events-aws-key.pem
  ca:
    file: ./certs/ca.pem

configs:
  envoy_proxy:
    file: ./envoy/envoy.yaml
  copy_script:
    file: ./scripts/copy_certs.sh

volumes:
  certbot-certificates:
  certbot-cmg-certificates:
  envoy-certificates:

networks:
  gitstafette:
    driver: bridge
    enable_ipv6: false